import { motion, useReducedMotion } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Check, Code2, Download, Globe2, Mail, Menu, Network, Server, ShieldCheck, X } from 'lucide-react'
import { useState } from 'react'
import portrait from './assets/srcn.png'
import xcitiumImage from './assets/xc.png'
import metasurfaceImage from './assets/metasurface.png'
import driversLicenseImage from './assets/ehliyet.png'
import resumePdf from '../assets/Sercan_EN.pdf'

const expertise = [{ icon: Network, number: '01', title: 'Network & Security', text: 'Enterprise networking, secure connectivity and firewall administration.', highlights: ['TCP/IP', 'DHCP', 'DNS', 'VLAN', 'LAN/WAN', 'VPN', 'Fortinet FortiGate — Firewall Policy Management, Access Control, SSL VPN Administration, Configuration Backup and Troubleshooting'] }, { icon: Server, number: '02', title: 'System Administration', text: 'Enterprise platforms, identity services, servers and virtualisation.', highlights: ['Microsoft 365', 'Exchange Online', 'Active Directory', 'Microsoft Entra ID', 'Windows Server', 'VMware vSphere', 'VMware vCenter', 'Hyper-V', 'VirtualBox'] }, { icon: ShieldCheck, number: '03', title: 'IT Operations', text: 'Service delivery, incident response, remote support and endpoint security.', highlights: ['IT Service Management (GLPI)', 'Incident Management', 'Remote Support', 'Endpoint Security (Xcitium)'] }]
const projects = [{ category: 'IEEE publication', title: 'Design of Wideband Metasurface Structure with the Aid of Bottom-Up Optimization', desc: 'S. Ozer, L. Kouhalvandi, L. Matekovits and M. Alibakhshikenari, "Design of Wideband Metasurface Structure with the Aid of BottomUp Optimization," 2024 International Conference on Electromagnetics in Advanced Applications (ICEAA), Lisbon, Portugal, 2024, pp. 316-319, doi: 10.1109/ICEAA61917.2024.10701815.', metric: 'ICEAA', label: '2024 publication', tone: 'blue', link: 'https://ieeexplore.ieee.org/document/10701815', image: metasurfaceImage }, { category: 'Cybersecurity', title: 'XCITIUM Endpoint Security', desc: 'Spearheaded the end-to-end deployment and configuration of the Xcitium cybersecurity platform for ~1,000 enterprise devices across the university. Resolved post-deployment technical issues by creating custom profiles and security rules within the Xcitium admin console. The system is currently active, successfully safeguarding the university network from cyber threats.', metric: '~1,000', label: 'protected devices', tone: 'violet', image: xcitiumImage }, { category: 'Mobile application', title: "Driver's License Exam Application", desc: 'This application was developed with Flutter and Dart using Android Studio, supported by Firebase infrastructure. Soon to be published on iOS and Google Play Store, the app provides practice exams and tests designed for candidates preparing for the driving license written exam.', metric: 'Flutter', label: 'mobile application', tone: 'green', image: driversLicenseImage }]
const experience = [{ period: '10/2025 — 07/2026', role: 'Assistant System Administrator', company: 'Doğuş University · Ümraniye, Istanbul', detail: 'Supported enterprise IT operations, systems administration and network infrastructure for approximately 19,000 users.', highlights: ['Managed user accounts, groups, licensing and access permissions across Microsoft 365 Admin Center, Active Directory and Microsoft Entra ID.', 'Supported system operations and IT service delivery within an enterprise infrastructure serving approximately 19,000 users.', 'Actively participated in the network migration from Juniper and 3Com infrastructure to Fortinet switching infrastructure.', 'Administered Fortinet FortiGate Firewall, including firewall policy management, VPN user administration, access control and configuration backup.', 'Troubleshot and resolved network issues related to VLAN, DHCP, DNS and IP addressing.', 'Managed Xcitium Endpoint Security across approximately 1,000 endpoints.', 'Implemented and configured the Linux-based GLPI IT Service Management (ITSM) platform, including initial deployment and system configuration for institutional use.'] }, { period: '12/2023 — 02/2024', role: 'IT Assistant Specialist', company: 'Ümraniye Municipality · Ümraniye, Istanbul', detail: 'Delivered first-level technical support and daily IT operational services for municipal end users.', highlights: ['Handled and resolved an average of 150+ monthly user support requests across hardware, software and network issues.', 'Achieved a 95% resolution rate for user tickets and escalated complex issues to higher-level IT teams when required.', 'Provided fast response to hardware, software and network-related issues to minimize system downtime.', 'Delivered first-level (L1) technical support to end users and supported daily IT operational processes.'] }, { period: '09/2013 — 08/2014', role: 'IT Helpdesk Intern', company: 'DemirDöküm · Çekmeköy, Istanbul', detail: 'Supported end users with hardware, Windows, Microsoft Office and foundational network troubleshooting.', highlights: ['Handled user support requests as a helpdesk intern and resolved basic network issues, including IP configuration and DHCP.', 'Provided fast support for hardware and infrastructure issues, including network connectivity, printers, IP cameras and IP phone systems.', 'Performed installation, updates and troubleshooting of Windows operating systems and Microsoft Office applications.'] }]
const education = [{ period: '2019 — 2024', title: 'B.Sc. in Electronics and Communication Engineering', place: 'Doğuş University, Istanbul · GPA: 2.92 / 4.00' }, { period: '2014 — 2016', title: 'A.S. in Electronics and Communication Technology', place: 'Istanbul University, Istanbul · GPA: 2.71 / 4.00' }]
const LinkedInIcon = ({ size = 16 }: { size?: number }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M7 8v9M7 5.5v.01M11 17v-5a3 3 0 0 1 6 0v5M11 12v5" /><rect x="3" y="3" width="18" height="18" rx="2" /></svg>
const Github = ({ size = 16 }: { size?: number }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7A5.4 5.4 0 0 0 19.4 4 5 5 0 0 0 19.3.5S18.2.1 15 1.8a13.4 13.4 0 0 0-7 0C4.8.1 3.7.5 3.7.5A5 5 0 0 0 3.6 4a5.4 5.4 0 0 0-1.4 3.7c0 5.4 3.5 6.6 6.8 7A4.8 4.8 0 0 0 8 18v4" /><path d="M8 19c-3 .9-3-1.5-4-2" /></svg>

function App() {
  const [open, setOpen] = useState(false)
  const [openExperience, setOpenExperience] = useState<string[]>([])
  const [openSkill, setOpenSkill] = useState<string[]>([])
  const reducedMotion = useReducedMotion()
  const reveal = reducedMotion ? {} : { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.6, ease: 'easeOut' as const } }
  const nav = [['#about', 'About'], ['#experience', 'Experience'], ['#projects', 'Projects'], ['#education', 'Education'], ['#skills', 'Skills']]
  return <main>
    <a className="skip-link" href="#content">Skip to content</a>
    <header className="site-header"><a className="brand" href="#top" aria-label="Sercan Ozer, home"><span className="brand-mark">S</span><span>Sercan Ozer</span></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([href, label]) => <a href={href} key={href}>{label}</a>)}</nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open ? <X /> : <Menu />}</button>{open && <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([href, label]) => <a onClick={() => setOpen(false)} href={href} key={href}>{label}</a>)}</nav>}</header>
    <div id="top" className="hero-shell"><section className="hero" id="content"><motion.h1 {...reveal} transition={{ ...reveal.transition, delay: .08 }}>Sercan<br /><em>Özer</em></motion.h1><motion.div {...reveal} transition={{ ...reveal.transition, delay: .16 }} className="hero-bottom"><div><p>IT System &amp; Network Engineer</p><div className="hero-links"><a className="cv-link" href={resumePdf} download="Sercan_Ozer_Resume.pdf"><Download size={16} /> Download Résumé</a><a href="mailto:sercan.ozer.28@gmail.com" aria-label="Email Sercan Ozer"><Mail size={18} /></a><a href="https://www.linkedin.com/in/sercanozer/" target="_blank" rel="noreferrer" aria-label="Sercan Ozer on LinkedIn"><LinkedInIcon size={18} /></a><a href="https://github.com/DeSiLencee" target="_blank" rel="noreferrer" aria-label="Sercan Ozer on GitHub"><Github size={18} /></a></div></div></motion.div></section><div className="hero-visual topology" aria-hidden="true"><svg viewBox="0 0 600 500" preserveAspectRatio="none"><path className="topology-line line-one" d="M90 290 L230 160 L370 260 L520 120" /><path className="topology-line line-two" d="M90 290 L280 375 L500 355" /><path className="topology-line line-three" d="M230 160 L280 375" /><path className="topology-line line-four" d="M370 260 L500 355" /><path className="topology-beam beam-one" d="M90 290 L230 160 L370 260 L520 120" /><path className="topology-beam beam-two" d="M90 290 L280 375 L500 355" /><path className="topology-beam beam-three" d="M230 160 L280 375" /></svg><div className="topology-node core-node"><Network size={23} /><span>CORE</span></div><div className="topology-node server-node"><Server size={21} /><span>SERVER</span></div><div className="topology-node firewall"><ShieldCheck size={21} /><span>FIREWALL</span></div><div className="topology-node storage-node"><Code2 size={21} /><span>STORAGE</span></div><div className="topology-node cloud-node"><Globe2 size={21} /><span>CLOUD</span></div></div></div>
    <section id="about" className="about section-pad"><motion.div {...reveal} className="about-art portrait-frame"><div className="portrait-ring" /><img src={portrait} alt="Sercan Özer" /><div className="portrait-beam" /></motion.div><motion.div {...reveal} className="about-copy"><p className="eyebrow">About me</p><p>IT professional with hands-on experience in Microsoft 365, Active Directory, Windows Server, and network infrastructure. Experienced in system administration, user management, and Fortinet Firewall operations, including security policy management and VPN administration. Passionate about developing my career as a System Administrator or Network Engineer, with a strong focus on enterprise infrastructure and network technologies.</p><ul><li><Check size={16} /> System Administration</li><li><Check size={16} /> Network Security &amp; Administration</li><li><Check size={16} /> IT Infrastructure</li></ul><div className="languages"><span>Languages</span><p>Turkish — Native &nbsp;·&nbsp; English — Professional working proficiency &nbsp;·&nbsp; German — Beginner</p></div></motion.div></section>
    <section id="experience" className="experience section-pad"><div className="section-top"><span className="eyebrow">Experience <sup>(03)</sup></span></div><div className="experience-cards">{experience.map((item, i) => { const isOpen = openExperience.includes(item.period); return <motion.article {...reveal} transition={{ ...reveal.transition, delay: i * .08 }} className={`experience-card ${isOpen ? 'is-open' : ''}`} key={item.period}><button type="button" onClick={() => setOpenExperience(current => current.includes(item.period) ? current.filter(period => period !== item.period) : [...current, item.period])} aria-expanded={isOpen}><span>{item.period}</span><h3>{item.role}</h3><strong>{item.company}</strong><p>{item.detail}</p><ArrowDownRight className="experience-arrow" size={20} /></button>{isOpen && <motion.div className="experience-glowbox" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}><p>Key contributions</p><ul>{item.highlights.map(highlight => <li key={highlight}><Check size={15} /> {highlight}</li>)}</ul></motion.div>}</motion.article> })}</div></section>
    <section id="projects" className="work section-pad"><div className="section-top"><span className="eyebrow">Selected projects <sup>(03)</sup></span></div><div className="project-grid">{projects.map((project, i) => <motion.article {...reveal} transition={{ ...reveal.transition, delay: i * .08 }} className={`project-card ${project.tone}`} key={project.title}><div className="project-visual">{project.image ? <img className="project-image" src={project.image} alt={project.title} /> : <div className="abstract-ui"><i /><i /><i /><b /></div>}</div><div className="project-content"><p>{project.category}</p><h3>{project.title}</h3><span>{project.desc}</span><div className="metric"><strong>{project.metric}</strong><small>{project.label}</small></div>{project.link && <a className="project-resource" href={project.link} target="_blank" rel="noreferrer">IEEE Link <ArrowUpRight size={15} /></a>}</div></motion.article>)}</div></section>
    <section id="education" className="education section-pad"><div className="section-top"><span className="eyebrow">Education <sup>(02)</sup></span></div><div className="education-grid">{education.map((item, i) => <motion.article {...reveal} transition={{ ...reveal.transition, delay: i * .08 }} key={item.title}><span>{item.period}</span><h3>{item.title}</h3><p>{item.place}</p></motion.article>)}</div><div id="skills" className="section-top skills-heading"><span className="eyebrow">Skills <sup>(03)</sup></span></div><div className="skills-cards">{expertise.map((item, i) => { const Icon = item.icon; const isOpen = openSkill.includes(item.number); return <motion.article {...reveal} transition={{ ...reveal.transition, delay: i * .08 }} className={`skill-card ${isOpen ? 'is-open' : ''}`} key={item.title}><button type="button" onClick={() => setOpenSkill(current => current.includes(item.number) ? current.filter(number => number !== item.number) : [...current, item.number])} aria-expanded={isOpen}><span>{item.number}</span><Icon aria-hidden="true" /><h3>{item.title}</h3><p>{item.text}</p><div className="expand-hint"><span>{isOpen ? 'Hide capabilities' : 'View capabilities'}</span><ArrowDownRight className="experience-arrow" size={20} /></div></button>{isOpen && <motion.div className="experience-glowbox" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}><p>Core capabilities</p><ul>{item.highlights.map(highlight => <li key={highlight}><Check size={15} /> {highlight}</li>)}</ul></motion.div>}</motion.article> })}</div></section>
    <section id="contact" className="contact contact-compact"><motion.div {...reveal}><p className="eyebrow">Contact</p><p className="contact-copy">Get in touch.</p><a className="email-link" href="mailto:sercan.ozer.28@gmail.com"><Mail size={18} /> sercan.ozer.28@gmail.com</a></motion.div><a className="contact-linkedin" href="https://www.linkedin.com/in/sercanozer/" target="_blank" rel="noreferrer"><LinkedInIcon size={18} /> LinkedIn</a></section><footer><span>© {new Date().getFullYear()} Sercan Ozer</span><span>Based in Istanbul, TR</span></footer>
  </main>
}
export default App
